# Generated by Django 5.1.2 on 2026-01-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_utilisateurs', models.PositiveIntegerField(default=0)),
                ('nombre_chapitres_termines', models.PositiveIntegerField(default=0)),
                ('temps_etude_total', models.PositiveIntegerField(default=0, help_text='Temps en minutes')),
                ('nombre_quiz_reussis', models.PositiveIntegerField(default=0)),
                ('moyenne_generale', models.FloatField(default=0.0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique globale',
                'verbose_name_plural': 'Statistiques globales',
            },
        ),
    ]
