# Generated by Django 5.1.2 on 2025-08-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentative', models.PositiveIntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('pourcentage', models.FloatField(blank=True, null=True)),
                ('temps_ecoule', models.PositiveIntegerField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('termine', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree_minutes', models.PositiveIntegerField()),
                ('nombre_questions', models.PositiveIntegerField()),
                ('note_passage', models.FloatField(default=50.0)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('melanger_questions', models.BooleanField(default=True)),
                ('melanger_reponses', models.BooleanField(default=True)),
                ('tentatives_autorisees', models.PositiveIntegerField(default=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='cours.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('explication', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('vrai_faux', 'Vrai/Faux'), ('texte_libre', 'Texte libre')], default='choix_unique', max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
            options={
                'ordering': ['quiz', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_reponse', models.TextField()),
                ('est_correcte', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='quiz.questionquiz')),
            ],
            options={
                'ordering': ['question', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_libre', models.TextField(blank=True)),
                ('temps_reponse', models.PositiveIntegerField(blank=True, null=True)),
                ('correcte', models.BooleanField(blank=True, null=True)),
                ('points_obtenus', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionquiz')),
                ('reponses_choisies', models.ManyToManyField(blank=True, to='quiz.reponsequestion')),
            ],
        ),
    ]
