# Generated by Django 5.1.2 on 2025-08-10 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativequiz',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentativequiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='reponseetudiant',
            name='tentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='quiz.tentativequiz'),
        ),
        migrations.AlterUniqueTogether(
            name='tentativequiz',
            unique_together={('etudiant', 'quiz', 'numero_tentative')},
        ),
        migrations.AlterUniqueTogether(
            name='reponseetudiant',
            unique_together={('tentative', 'question')},
        ),
    ]
