# Generated by Django 5.1.2 on 2026-01-23 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la configuration', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description de la configuration', null=True)),
                ('pourcentage_commission_default', models.DecimalField(decimal_places=2, default=10.0, help_text='Pourcentage de commission par défaut', max_digits=5)),
                ('seuil_retrait_minimum', models.DecimalField(decimal_places=2, default=25000.0, help_text='Seuil minimum pour les retraits (en FCFA)', max_digits=10)),
                ('montant_retrait_multiple', models.DecimalField(decimal_places=2, default=5000.0, help_text='Montant multiple pour les retraits (en FCFA)', max_digits=10)),
                ('methodes_paiement_autorisees', models.TextField(default='wave,orange_money,mtn_money,moov_money', help_text='Méthodes de paiement autorisées (séparées par des virgules)')),
                ('validation_automatique_retrait', models.BooleanField(default=False, help_text='Validation automatique des retraits')),
                ('delai_traitement_retrait_heures', models.PositiveIntegerField(default=24, help_text='Délai de traitement des retraits en heures')),
                ('actif', models.BooleanField(default=True, help_text='Configuration active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Partenaire',
                'verbose_name_plural': 'Configurations Partenaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('eleve', 'Élève'), ('parent', 'Parent'), ('partenaire', 'Partenaire')], default='eleve', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('matricule', models.CharField(blank=True, help_text="Numéro matricule de l'étudiant", max_length=20, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True)),
                ('avatar_choisi', models.CharField(choices=[('avatar1', 'Avatar 1 - Étudiant'), ('avatar2', 'Avatar 2 - Étudiante'), ('avatar3', 'Avatar 3 - Professeur'), ('avatar4', 'Avatar 4 - Scientifique'), ('avatar5', 'Avatar 5 - Artiste'), ('avatar6', 'Avatar 6 - Sportif'), ('avatar7', 'Avatar 7 - Génie')], default='avatar1', help_text="Avatar prédéfini choisi par l'utilisateur", max_length=10)),
                ('photo_profil', models.ImageField(blank=True, help_text='Photo de profil personnalisée', null=True, upload_to='photos_profil/')),
                ('code_parrainage', models.CharField(blank=True, help_text="Code de parrainage unique de l'utilisateur", max_length=20, null=True, unique=True)),
                ('code_parrain_utilise', models.CharField(blank=True, help_text="Code de parrainage utilisé lors de l'inscription", max_length=20, null=True)),
                ('objectifs_apprentissage', models.TextField(blank=True, help_text="Objectifs d'apprentissage définis par le parent", null=True)),
                ('commission_retiree', models.DecimalField(decimal_places=2, default=0, help_text='Commission retirée', max_digits=10)),
                ('commission_totale_accumulee', models.DecimalField(decimal_places=2, default=0, help_text='Commission totale accumulée', max_digits=10)),
                ('methode_paiement', models.CharField(blank=True, help_text='Méthode de paiement préférée', max_length=50, null=True)),
                ('telephone_paiement', models.CharField(blank=True, help_text='Téléphone pour paiement', max_length=20, null=True)),
                ('nombre_abonnements_parraines', models.PositiveIntegerField(default=0, help_text="Nombre d'abonnements parrainés")),
                ('nombre_filleuls_uniques', models.PositiveIntegerField(default=0, help_text='Nombre de filleuls uniques')),
                ('derniere_activite', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_verifie', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_structure.niveauscolaire')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_abonnement', models.DecimalField(decimal_places=2, help_text="Montant de l'abonnement (en FCFA)", max_digits=10)),
                ('montant_commission', models.DecimalField(decimal_places=2, help_text='Montant de la commission (en FCFA)', max_digits=10)),
                ('abonnement_id', models.PositiveIntegerField(blank=True, help_text="ID de l'abonnement généré", null=True)),
                ('date_commission', models.DateTimeField(auto_now_add=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-date_commission'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionEnAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('code_parrain_utilise', models.CharField(blank=True, max_length=8, null=True, verbose_name='Code de parrainage utilisé')),
                ('otp', models.CharField(max_length=6)),
                ('otp_expires_at', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_structure.niveauscolaire')),
            ],
        ),
        migrations.CreateModel(
            name='LienParentEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, help_text="Date de confirmation du lien par l'enfant", null=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_enfant', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien Parent-Enfant',
                'verbose_name_plural': 'Liens Parent-Enfant',
                'ordering': ['-date_creation'],
                'unique_together': {('parent', 'enfant')},
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='enfants_lies',
            field=models.ManyToManyField(blank=True, related_name='parents_lies', through='utilisateurs.LienParentEnfant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PreferencesUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('rappels_etude', models.BooleanField(default=True, verbose_name="Rappels d'étude")),
                ('partage_progres', models.BooleanField(default=False, verbose_name='Partage des progrès')),
                ('profil_public', models.BooleanField(default=False, verbose_name='Profil public')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=10, verbose_name='Langue')),
                ('pays', models.CharField(choices=[("Côte d'Ivoire", "Côte d'Ivoire"), ('France', 'France'), ('Sénégal', 'Sénégal'), ('Mali', 'Mali'), ('Burkina Faso', 'Burkina Faso'), ('Togo', 'Togo'), ('Bénin', 'Bénin'), ('Niger', 'Niger'), ('Cameroun', 'Cameroun'), ('Gabon', 'Gabon'), ('Congo', 'Congo'), ('RDC', 'République Démocratique du Congo'), ('Autre', 'Autre')], default="Côte d'Ivoire", max_length=50, verbose_name='Pays')),
                ('temps_session_etude', models.PositiveIntegerField(default=45, verbose_name="Durée session d'étude (minutes)")),
                ('pause_session', models.PositiveIntegerField(default=15, verbose_name='Durée pause (minutes)')),
                ('notification_quiz', models.BooleanField(default=True, verbose_name='Notifications de quiz')),
                ('notification_examen', models.BooleanField(default=True, verbose_name="Notifications d'examens")),
                ('notification_badge', models.BooleanField(default=True, verbose_name='Notifications de badges')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
        migrations.CreateModel(
            name='RetraitCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant du retrait (en FCFA)', max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('traite', 'Traité')], default='en_attente', max_length=20)),
                ('methode_paiement', models.CharField(help_text='Méthode de paiement utilisée', max_length=20)),
                ('telephone_paiement', models.CharField(help_text='Numéro de téléphone pour le paiement', max_length=20)),
                ('numero_wave', models.CharField(blank=True, help_text='Numéro Wave pour le retrait', max_length=20, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes de traitement')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retrait de Commission',
                'verbose_name_plural': 'Retraits de Commissions',
                'ordering': ['-date_demande'],
            },
        ),
    ]
