# Generated by Django 5.1.2 on 2025-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, help_text="Numéro matricule de l'étudiant", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True),
        ),
    ]
