# Generated by Django 5.1.2 on 2025-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_matricule_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar_choisi',
            field=models.CharField(choices=[('avatar1', 'Avatar 1 - Étudiant'), ('avatar2', 'Avatar 2 - Étudiante'), ('avatar3', 'Avatar 3 - Professeur'), ('avatar4', 'Avatar 4 - Scientifique'), ('avatar5', 'Avatar 5 - Artiste'), ('avatar6', 'Avatar 6 - Sportif'), ('avatar7', 'Avatar 7 - Génie')], default='avatar1', help_text="Avatar prédéfini choisi par l'utilisateur", max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil personnalisée', null=True, upload_to='photos_profil/'),
        ),
    ]
