# Generated by Django 5.1.2 on 2025-08-30 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_avatar_choisi_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('notifications_push', models.BooleanField(default=True, verbose_name='Notifications push')),
                ('rappels_etude', models.BooleanField(default=True, verbose_name="Rappels d'étude")),
                ('mode_sombre', models.BooleanField(default=False, verbose_name='Mode sombre')),
                ('sons_interface', models.BooleanField(default=True, verbose_name="Sons d'interface")),
                ('partage_progres', models.BooleanField(default=False, verbose_name='Partage des progrès')),
                ('profil_public', models.BooleanField(default=False, verbose_name='Profil public')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=10, verbose_name='Langue')),
                ('pays', models.CharField(choices=[("Côte d'Ivoire", "Côte d'Ivoire"), ('France', 'France'), ('Sénégal', 'Sénégal'), ('Mali', 'Mali'), ('Burkina Faso', 'Burkina Faso'), ('Togo', 'Togo'), ('Bénin', 'Bénin'), ('Niger', 'Niger'), ('Cameroun', 'Cameroun'), ('Gabon', 'Gabon'), ('Congo', 'Congo'), ('RDC', 'République Démocratique du Congo'), ('Autre', 'Autre')], default="Côte d'Ivoire", max_length=50, verbose_name='Pays')),
                ('temps_session_etude', models.PositiveIntegerField(default=45, verbose_name="Durée session d'étude (minutes)")),
                ('pause_session', models.PositiveIntegerField(default=15, verbose_name='Durée pause (minutes)')),
                ('notification_quiz', models.BooleanField(default=True, verbose_name='Notifications de quiz')),
                ('notification_examen', models.BooleanField(default=True, verbose_name="Notifications d'examens")),
                ('notification_badge', models.BooleanField(default=True, verbose_name='Notifications de badges')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
    ]
