# Generated by Django 5.1.2 on 2025-08-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_preferencesutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencesutilisateur',
            name='mode_sombre',
        ),
        migrations.RemoveField(
            model_name='preferencesutilisateur',
            name='notifications_push',
        ),
        migrations.RemoveField(
            model_name='preferencesutilisateur',
            name='sons_interface',
        ),
    ]
