# Generated by Django 5.1.2 on 2025-08-30 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_remove_preferencesutilisateur_mode_sombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRappelEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log rappel d'étude",
                'verbose_name_plural': "Logs rappels d'étude",
                'unique_together': {('utilisateur', 'date_envoi')},
            },
        ),
    ]
