# Generated by Django 5.1.2 on 2025-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_lograppeletude'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_parrain_utilise',
            field=models.CharField(blank=True, help_text="Code de parrainage utilisé lors de l'inscription", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_parrainage',
            field=models.CharField(blank=True, help_text="Code de parrainage unique de l'utilisateur", max_length=20, null=True, unique=True),
        ),
    ]
