# Generated by Django 5.1.2 on 2025-09-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_utilisateur_code_parrain_utilise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionenattente',
            name='code_parrain_utilise',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Code de parrainage utilisé'),
        ),
    ]
