# Generated by Django 5.1.2 on 2025-09-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_inscriptionenattente_code_parrain_utilise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, help_text="Numéro matricule de l'étudiant", max_length=20, null=True, unique=True),
        ),
    ]
