# Generated by Django 5.1.2 on 2025-09-06 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_alter_utilisateur_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeParente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Expirée')], default='en_attente', help_text='Statut de la demande', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(help_text="Date d'expiration de la demande (7 jours après création)")),
                ('message_parent', models.TextField(blank=True, help_text='Message optionnel du parent', null=True)),
                ('enfant', models.ForeignKey(help_text='Enfant concerné par la demande', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_parente_recues', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='Parent qui fait la demande', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_parente_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de parenté',
                'verbose_name_plural': 'Demandes de parenté',
                'ordering': ['-date_creation'],
                'unique_together': {('parent', 'enfant')},
            },
        ),
        migrations.CreateModel(
            name='LienParentEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, help_text='Lien actif ou désactivé')),
                ('enfant', models.ForeignKey(help_text='Enfant', limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='parents_lies', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='Parent', limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='enfants_lies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien parent-enfant',
                'verbose_name_plural': 'Liens parent-enfant',
                'ordering': ['-date_creation'],
                'unique_together': {('parent', 'enfant')},
            },
        ),
    ]
