# Generated by Django 5.1.2 on 2025-09-06 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_demandeparente_lienparentenfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code de sécurité à 6 chiffres', max_length=6)),
                ('action', models.CharField(help_text='Action pour laquelle le code est généré', max_length=50)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField(help_text="Date d'expiration du code (5 minutes)")),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_securite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de sécurité',
                'verbose_name_plural': 'Codes de sécurité',
                'ordering': ['-cree_le'],
            },
        ),
    ]
