# Generated by Django 5.1.2 on 2025-09-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_codesecurite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSecurite',
        ),
    ]
