# Generated by Django 5.1.2 on 2025-09-07 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0012_delete_codesecurite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('cours_complete', 'Cours complété'), ('chapitre_termine', 'Chapitre terminé'), ('quiz_reussi', 'Quiz réussi'), ('quiz_echec', 'Quiz échoué'), ('exercice_complete', 'Exercice complété'), ('examen_passe', 'Examen passé'), ('examen_reussi', 'Examen réussi'), ('badge_obtenu', 'Badge obtenu'), ('score_ameliore', 'Score amélioré'), ('connexion', 'Connexion'), ('progression_niveau', 'Progression de niveau'), ('temps_etude', "Temps d'étude")], help_text="Type d'activité effectuée", max_length=20)),
                ('titre', models.CharField(help_text="Titre descriptif de l'activité", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'activité", null=True)),
                ('matiere', models.CharField(blank=True, help_text="Matière concernée par l'activité", max_length=100, null=True)),
                ('chapitre', models.CharField(blank=True, help_text='Chapitre ou section concerné', max_length=200, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Score obtenu (pour quiz, examens, etc.)', null=True)),
                ('score_max', models.IntegerField(blank=True, help_text='Score maximum possible', null=True)),
                ('duree_minutes', models.IntegerField(blank=True, help_text="Durée de l'activité en minutes", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Données supplémentaires sur l'activité")),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date et heure de l'activité")),
                ('utilisateur', models.ForeignKey(help_text="Utilisateur qui a effectué l'activité", on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateur',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', '-date_creation'], name='utilisateur_utilisa_013b42_idx'), models.Index(fields=['type_activite', '-date_creation'], name='utilisateur_type_ac_06a53a_idx'), models.Index(fields=['matiere', '-date_creation'], name='utilisateur_matiere_64adbd_idx')],
            },
        ),
    ]
