# Generated by Django 5.1.2 on 2025-09-11 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0013_activiteutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('eleve', 'Élève'), ('parent', 'Parent'), ('partenaire', 'Partenaire')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_paiement', models.CharField(help_text='Numéro de téléphone pour recevoir les paiements', max_length=20)),
                ('methode_paiement', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money')], default='wave', help_text='Méthode de paiement préférée', max_length=20)),
                ('pourcentage_commission', models.DecimalField(decimal_places=2, default=10.0, help_text='Pourcentage de commission sur les abonnements (ex: 10.00 pour 10%)', max_digits=5)),
                ('seuil_retrait_minimum', models.DecimalField(decimal_places=2, default=25000.0, help_text='Montant minimum pour effectuer un retrait (en FCFA)', max_digits=10)),
                ('montant_retrait_multiple', models.DecimalField(decimal_places=2, default=5000.0, help_text='Montant multiple pour les retraits (en FCFA)', max_digits=10)),
                ('commission_totale_accumulee', models.DecimalField(decimal_places=2, default=0.0, help_text='Total des commissions accumulées (en FCFA)', max_digits=12)),
                ('commission_retiree', models.DecimalField(decimal_places=2, default=0.0, help_text='Total des commissions retirées (en FCFA)', max_digits=12)),
                ('nombre_abonnements_parraines', models.PositiveIntegerField(default=0, help_text="Nombre d'abonnements générés par ce partenaire")),
                ('actif', models.BooleanField(default=True, help_text='Partenaire actif ou non')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_commission', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partenaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_abonnement', models.DecimalField(decimal_places=2, help_text="Montant de l'abonnement (en FCFA)", max_digits=10)),
                ('montant_commission', models.DecimalField(decimal_places=2, help_text='Montant de la commission (en FCFA)', max_digits=10)),
                ('abonnement_id', models.PositiveIntegerField(blank=True, help_text="ID de l'abonnement généré", null=True)),
                ('date_commission', models.DateTimeField(auto_now_add=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='utilisateurs.partenaire')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-date_commission'],
            },
        ),
        migrations.CreateModel(
            name='RetraitCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant retiré (en FCFA)', max_digits=10)),
                ('methode_paiement', models.CharField(help_text='Méthode de paiement utilisée', max_length=20)),
                ('telephone_paiement', models.CharField(help_text='Numéro de téléphone pour le paiement', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence de la transaction de paiement', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes sur le retrait', null=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='utilisateurs.partenaire')),
            ],
            options={
                'verbose_name': 'Retrait de commission',
                'verbose_name_plural': 'Retraits de commission',
                'ordering': ['-date_demande'],
            },
        ),
    ]
