# Generated by Django 5.1.2 on 2026-01-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_alter_utilisateur_role_partenaire_commission_and_more'),
    ]

    operations = [
    ]
