# Generated by Django 5.1.2 on 2025-09-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_alter_utilisateur_role_partenaire_commission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la configuration', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la configuration')),
                ('pourcentage_commission_default', models.DecimalField(decimal_places=2, default=10.0, help_text='Pourcentage de commission par défaut', max_digits=5)),
                ('seuil_retrait_minimum', models.DecimalField(decimal_places=2, default=25000.0, help_text='Montant minimum pour effectuer un retrait (FCFA)', max_digits=12)),
                ('montant_retrait_multiple', models.DecimalField(decimal_places=2, default=5000.0, help_text='Multiple de retrait (FCFA)', max_digits=12)),
                ('methodes_paiement_autorisees', models.JSONField(default=list, help_text='Méthodes de paiement autorisées')),
                ('validation_automatique_retrait', models.BooleanField(default=False, help_text='Validation automatique des retraits')),
                ('delai_traitement_retrait_heures', models.PositiveIntegerField(default=48, help_text='Délai de traitement des retraits (heures)')),
                ('actif', models.BooleanField(default=True, help_text='Configuration active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Partenaire',
                'verbose_name_plural': 'Configurations Partenaire',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='montant_retrait_multiple',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='pourcentage_commission',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='seuil_retrait_minimum',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='pourcentage_commission_personnalise',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de commission personnalisé (optionnel)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='configuration_personnalisee',
            field=models.ForeignKey(blank=True, help_text='Configuration personnalisée (optionnelle)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.configurationpartenaire'),
        ),
    ]
