# Generated by Django 5.1.2 on 2025-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0015_configurationpartenaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='nombre_filleuls_uniques',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de filleuls uniques de ce partenaire'),
        ),
    ]
