# Generated by Django 5.1.2 on 2025-09-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0016_partenaire_nombre_filleuls_uniques'),
    ]

    operations = [
    ]
