# Generated by Django 5.1.2 on 2025-09-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_auto_20250912_1708'),
    ]

    operations = [
        # Créer la table ConfigurationPartenaire
        migrations.CreateModel(
            name='ConfigurationPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, help_text='Nom de la configuration')),
                ('pourcentage_commission', models.DecimalField(decimal_places=2, default=10.0, help_text='Pourcentage de commission par défaut', max_digits=5)),
                ('seuil_retrait_minimum', models.DecimalField(decimal_places=2, default=25000.0, help_text='Seuil minimum pour les retraits (en FCFA)', max_digits=10)),
                ('montant_retrait_multiple', models.DecimalField(decimal_places=2, default=5000.0, help_text='Montant multiple pour les retraits (en FCFA)', max_digits=10)),
                ('methodes_paiement', models.JSONField(default=list, help_text='Méthodes de paiement disponibles')),
                ('actif', models.BooleanField(default=True, help_text='Configuration active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Partenaire',
                'verbose_name_plural': 'Configurations Partenaires',
                'ordering': ['-date_creation'],
            },
        ),
        # Créer la table LienParentEnfant
        migrations.CreateModel(
            name='LienParentEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes sur la relation parent-enfant', null=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_enfant', to='utilisateurs.utilisateur')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_parent', to='utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Lien Parent-Enfant',
                'verbose_name_plural': 'Liens Parent-Enfant',
                'ordering': ['-date_creation'],
                'unique_together': {('parent', 'enfant')},
            },
        ),
        # Ajouter le champ enfants_lies à Utilisateur
        migrations.AddField(
            model_name='utilisateur',
            name='enfants_lies',
            field=models.ManyToManyField(blank=True, related_name='parents_lies', through='utilisateurs.LienParentEnfant', to='utilisateurs.utilisateur'),
        ),
    ]
