# Generated by Django 5.1.2 on 2025-09-15 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0018_auto_20250912_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activiteutilisateur',
            name='utilisateur',
        ),
        migrations.AlterUniqueTogether(
            name='demandeparente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='demandeparente',
            name='enfant',
        ),
        migrations.RemoveField(
            model_name='demandeparente',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='lograppeletude',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lograppeletude',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='configuration_personnalisee',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='retraitcommission',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReinitialisationMotDePasse',
        ),
        migrations.AlterModelOptions(
            name='retraitcommission',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Retrait de Commission', 'verbose_name_plural': 'Retraits de Commissions'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='configurationpartenaire',
            old_name='pourcentage_commission',
            new_name='pourcentage_commission_default',
        ),
        migrations.RemoveField(
            model_name='configurationpartenaire',
            name='methodes_paiement',
        ),
        migrations.RemoveField(
            model_name='lienparentenfant',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='lienparentenfant',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='retraitcommission',
            name='reference_transaction',
        ),
        migrations.AddField(
            model_name='configurationpartenaire',
            name='delai_traitement_retrait_heures',
            field=models.PositiveIntegerField(default=24, help_text='Délai de traitement des retraits en heures'),
        ),
        migrations.AddField(
            model_name='configurationpartenaire',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la configuration', null=True),
        ),
        migrations.AddField(
            model_name='configurationpartenaire',
            name='methodes_paiement_autorisees',
            field=models.TextField(default='wave,orange_money,mtn_money,moov_money', help_text='Méthodes de paiement autorisées (séparées par des virgules)'),
        ),
        migrations.AddField(
            model_name='configurationpartenaire',
            name='validation_automatique_retrait',
            field=models.BooleanField(default=False, help_text='Validation automatique des retraits'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='commission_retiree',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission retirée', max_digits=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='commission_totale_accumulee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission totale accumulée', max_digits=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='methode_paiement',
            field=models.CharField(blank=True, help_text='Méthode de paiement préférée', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nombre_abonnements_parraines',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'abonnements parrainés"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nombre_filleuls_uniques',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de filleuls uniques'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone_paiement',
            field=models.CharField(blank=True, help_text='Téléphone pour paiement', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='retraitcommission',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant du retrait (en FCFA)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='retraitcommission',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes de traitement'),
        ),
        migrations.AlterField(
            model_name='retraitcommission',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('traite', 'Traité')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_activite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='objectifs_apprentissage',
            field=models.TextField(blank=True, help_text="Objectifs d'apprentissage définis par le parent", null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('eleve', 'Élève'), ('parent', 'Parent'), ('partenaire', 'Partenaire')], default='eleve', max_length=20),
        ),
        migrations.DeleteModel(
            name='ActiviteUtilisateur',
        ),
        migrations.DeleteModel(
            name='DemandeParente',
        ),
        migrations.DeleteModel(
            name='LogRappelEtude',
        ),
        migrations.DeleteModel(
            name='Partenaire',
        ),
    ]
