# Generated by Django 5.1.2 on 2025-09-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0019_remove_activiteutilisateur_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitcommission',
            name='numero_wave',
            field=models.CharField(blank=True, help_text='Numéro Wave pour le retrait', max_length=20, null=True),
        ),
    ]
