# Generated by Django 5.1.2 on 2026-01-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0020_retraitcommission_numero_wave'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienparentenfant',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, help_text="Date de confirmation du lien par l'enfant", null=True),
        ),
    ]
