# Generated by Django 5.1.2 on 2026-01-23 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu'), ('essai', 'Essai gratuit')], default='actif', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('wave_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wave_payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('wave_payment_date', models.DateTimeField(blank=True, null=True)),
                ('est_essai_gratuit', models.BooleanField(default=False)),
                ('date_fin_essai', models.DateTimeField(blank=True, null=True)),
                ('renouvellement_auto', models.BooleanField(default=False)),
                ('source_parrainage', models.BooleanField(default=False, help_text="True si l'abonnement provient du système de parrainage")),
                ('date_renouvellement', models.DateTimeField(blank=True, help_text='Date du dernier renouvellement', null=True)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='BonusParrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_accumules', models.PositiveIntegerField(default=0, help_text='Nombre de semaines gratuites accumulées')),
                ('bonus_utilises', models.PositiveIntegerField(default=0, help_text='Nombre de bonus déjà utilisés')),
                ('date_dernier_bonus', models.DateTimeField(auto_now=True, help_text='Date du dernier bonus reçu')),
            ],
            options={
                'verbose_name': 'Bonus de parrainage',
                'verbose_name_plural': 'Bonus de parrainage',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRenouvellement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_renouvellement', models.DateTimeField(auto_now_add=True, help_text='Date du renouvellement')),
                ('duree_ajoutee', models.PositiveIntegerField(help_text='Nombre de jours ajoutés')),
                ('montant_renouvellement', models.DecimalField(decimal_places=2, help_text='Montant du renouvellement', max_digits=10)),
            ],
            options={
                'verbose_name': 'Historique de renouvellement',
                'verbose_name_plural': 'Historiques de renouvellements',
                'ordering': ['-date_renouvellement'],
            },
        ),
        migrations.CreateModel(
            name='PackAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_pack', models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('premium', 'Premium'), ('special', 'Pack Spécial'), ('famille', 'Pack Familial')], max_length=20)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('periode', models.CharField(choices=[('semaine', 'Semaine'), ('mois', 'Mois'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('annee', 'Année')], max_length=20)),
                ('duree_jours', models.IntegerField(help_text='Durée en jours')),
                ('actif', models.BooleanField(default=True)),
                ('pack_special', models.BooleanField(default=False)),
                ('reduction_pourcentage', models.IntegerField(default=0, help_text='Réduction en pourcentage')),
                ('conditions_speciales', models.TextField(blank=True, null=True)),
                ('offre_semaine_gratuite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Pack d'abonnement",
                'verbose_name_plural': "Packs d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='PackFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_familial', models.CharField(choices=[('familial_2', 'Famille 2 enfants'), ('familial_3', 'Famille 3+ enfants'), ('familial_4', 'Famille 4+ enfants')], default='familial_2', max_length=20)),
                ('nombre_enfants', models.IntegerField(default=2)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('periode', models.CharField(choices=[('semaine', 'Semaine'), ('mois', 'Mois'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('annee', 'Année')], default='mois', max_length=20)),
                ('duree_jours', models.IntegerField(default=30, help_text='Durée en jours')),
                ('actif', models.BooleanField(default=True)),
                ('pack_familial', models.BooleanField(default=True)),
                ('reduction_pourcentage', models.IntegerField(default=20, help_text='Réduction en pourcentage')),
                ('conditions_speciales', models.TextField(blank=True, null=True)),
                ('offre_semaine_gratuite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pack familial',
                'verbose_name_plural': 'Packs familiaux',
            },
        ),
        migrations.CreateModel(
            name='PackPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cours_par_mois', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('max_quiz_par_mois', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('max_examens_par_mois', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('acces_cours_premium', models.BooleanField(default=False, help_text='Accès aux cours premium')),
                ('acces_ia_standard', models.BooleanField(default=False, help_text='Support IA standard')),
                ('acces_ia_prioritaire', models.BooleanField(default=False, help_text='Support IA prioritaire')),
                ('acces_certificats', models.BooleanField(default=False, help_text='Accès aux certificats')),
                ('acces_contenu_hors_ligne', models.BooleanField(default=False, help_text='Téléchargement de contenu')),
                ('acces_communautaire', models.BooleanField(default=False, help_text='Accès au forum communautaire')),
                ('support_prioritaire', models.BooleanField(default=False, help_text='Support prioritaire')),
                ('acces_prioritaire_nouveautes', models.BooleanField(default=False, help_text='Accès prioritaire aux nouveautés')),
                ('specialisation_examens', models.BooleanField(default=False, help_text='Spécialisé pour les examens')),
                ('contenu_examens_prioritaire', models.BooleanField(default=False, help_text='Contenu examens prioritaire')),
                ('nombre_enfants_max', models.PositiveIntegerField(default=0, help_text="Nombre maximum d'enfants")),
                ('profils_separes', models.BooleanField(default=False, help_text='Profils séparés pour chaque enfant')),
                ('suivi_familial', models.BooleanField(default=False, help_text='Suivi familial')),
                ('upgrade_reminder', models.BooleanField(default=False, help_text="Rappels d'upgrade")),
                ('teaser_content', models.BooleanField(default=False, help_text='Contenu teaser premium')),
                ('restriction_temps', models.BooleanField(default=False, help_text='Restriction temporelle')),
                ('restriction_contenu', models.BooleanField(default=False, help_text='Restriction de contenu')),
                ('restriction_examens', models.BooleanField(default=False, help_text="Restriction d'examens")),
                ('message_restriction', models.TextField(default='Vous avez atteint votre limite. Passez à un pack supérieur !', help_text='Message affiché quand les restrictions sont atteintes')),
                ('bonus_parrainage', models.BooleanField(default=False, help_text='Bonus pour parrainage')),
                ('bonus_inscription', models.BooleanField(default=False, help_text='Bonus pour inscription')),
                ('bonus_conversion_parrainage', models.BooleanField(default=False, help_text='Bonus de conversion parrainage')),
                ('bonus_conversion_standard', models.BooleanField(default=False, help_text='Bonus de conversion standard')),
                ('bonus_annuel', models.BooleanField(default=False, help_text='Bonus annuel')),
                ('acces_exclusif', models.BooleanField(default=False, help_text='Contenu exclusif')),
                ('source_parrainage', models.BooleanField(default=False, help_text='Source parrainage')),
                ('source_inscription', models.BooleanField(default=False, help_text='Source inscription')),
            ],
            options={
                'verbose_name': 'Permissions du pack',
                'verbose_name_plural': 'Permissions des packs',
            },
        ),
        migrations.CreateModel(
            name='PaiementWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('wave_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('wave_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('wave_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pack_id', models.IntegerField(blank=True, help_text='ID du pack à créer après paiement', null=True)),
                ('utilisateur_id', models.IntegerField(blank=True, help_text="ID de l'utilisateur", null=True)),
                ('parent_id', models.IntegerField(blank=True, help_text='ID du parent qui effectue le paiement (pour les abonnements enfants)', null=True)),
                ('renouvellement_auto', models.BooleanField(default=False, help_text='Renouvellement automatique')),
                ('callback_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Paiement Wave',
                'verbose_name_plural': 'Paiements Wave',
            },
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_parrainage', models.CharField(help_text='Code de parrainage utilisé', max_length=20)),
                ('date_parrainage', models.DateTimeField(auto_now_add=True, help_text='Date de création du parrainage')),
                ('bonus_attribue', models.BooleanField(default=False, help_text='True si le bonus a été attribué au parrain')),
                ('date_bonus_attribue', models.DateTimeField(blank=True, help_text="Date d'attribution du bonus", null=True)),
                ('filleul_bonus_attribue', models.BooleanField(default=False, help_text='True si le bonus a été attribué au filleul')),
                ('date_filleul_bonus', models.DateTimeField(blank=True, help_text="Date d'attribution du bonus au filleul", null=True)),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
            },
        ),
    ]
