# Generated by Django 5.1.2 on 2025-09-01 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_pack', models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('premium', 'Premium'), ('special', 'Pack Spécial')], max_length=20)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('periode', models.CharField(choices=[('semaine', 'Semaine'), ('mois', 'Mois'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('annee', 'Année')], max_length=20)),
                ('duree_jours', models.IntegerField(help_text='Durée en jours')),
                ('actif', models.BooleanField(default=True)),
                ('pack_special', models.BooleanField(default=False)),
                ('reduction_pourcentage', models.IntegerField(default=0, help_text='Réduction en pourcentage')),
                ('conditions_speciales', models.TextField(blank=True, null=True)),
                ('cours_limites', models.IntegerField(default=0, help_text='0 = illimité')),
                ('quiz_limites', models.IntegerField(default=0, help_text='0 = illimité')),
                ('examens_inclus', models.BooleanField(default=False)),
                ('certificats_inclus', models.BooleanField(default=False)),
                ('support_ia_prioritaire', models.BooleanField(default=False)),
                ('contenu_hors_ligne', models.BooleanField(default=False)),
                ('offre_semaine_gratuite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Pack d'abonnement",
                'verbose_name_plural': "Packs d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='PackFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_enfants', models.IntegerField(default=2)),
                ('reduction_pourcentage', models.IntegerField(default=20)),
                ('description', models.TextField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pack familial',
                'verbose_name_plural': 'Packs familiaux',
            },
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='montant',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='date_fin_essai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='est_essai_gratuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='renouvellement_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu'), ('essai', 'Essai gratuit')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='wave_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='wave_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='wave_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonnements.packabonnement'),
        ),
        migrations.CreateModel(
            name='PaiementWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('wave_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('wave_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('wave_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnements.abonnement')),
            ],
            options={
                'verbose_name': 'Paiement Wave',
                'verbose_name_plural': 'Paiements Wave',
            },
        ),
        migrations.CreateModel(
            name='UtilisationAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cours_suivis', models.IntegerField(default=0)),
                ('quiz_realises', models.IntegerField(default=0)),
                ('examens_passes', models.IntegerField(default=0)),
                ('temps_etude_minutes', models.IntegerField(default=0)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnements.abonnement')),
            ],
            options={
                'verbose_name': 'Utilisation abonnement',
                'verbose_name_plural': 'Utilisations abonnements',
                'unique_together': {('abonnement', 'date')},
            },
        ),
    ]
