# Generated by Django 5.1.2 on 2026-01-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonusparrainage',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_parrainage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquerenouvellement',
            name='abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renouvellements', to='abonnements.abonnement'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonnements.packabonnement'),
        ),
        migrations.AddField(
            model_name='packpermissions',
            name='pack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='abonnements.packabonnement'),
        ),
        migrations.AddField(
            model_name='paiementwave',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonnements.abonnement'),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='filleul',
            field=models.OneToOneField(help_text='Utilisateur parrainé', on_delete=django.db.models.deletion.CASCADE, related_name='parrain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='parrain',
            field=models.ForeignKey(help_text='Utilisateur qui parraine', on_delete=django.db.models.deletion.CASCADE, related_name='filleuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='parrainage',
            unique_together={('parrain', 'filleul')},
        ),
    ]
