# Generated by Django
from django.db import migrations

def create_initial_packs(apps, schema_editor):
    PackAbonnement = apps.get_model('abonnements', 'PackAbonnement')
    PackFamilial = apps.get_model('abonnements', 'PackFamilial')
    
    # Packs par défaut
    packs = [
        {
            'nom': 'Gratuit',
            'type_pack': 'gratuit',
            'description': 'Accès limité aux fonctionnalités de base',
            'prix': 0,
            'periode': 'mois',
            'duree_jours': 30,
            'cours_limites': 5,
            'quiz_limites': 10,
            'examens_inclus': False,
            'certificats_inclus': False,
            'support_ia_prioritaire': False,
            'contenu_hors_ligne': False,
            'offre_semaine_gratuite': False,
            'pack_special': False,
        },
        {
            'nom': 'Standard',
            'type_pack': 'standard',
            'description': 'Accès étendu aux cours et quiz',
            'prix': 500,
            'periode': 'semaine',
            'duree_jours': 7,
            'cours_limites': 50,
            'quiz_limites': 0,  # illimité
            'examens_inclus': True,
            'certificats_inclus': False,
            'support_ia_prioritaire': False,
            'contenu_hors_ligne': False,
            'offre_semaine_gratuite': True,
            'pack_special': False,
        },
        {
            'nom': 'Premium',
            'type_pack': 'premium',
            'description': 'Accès complet à toutes les fonctionnalités',
            'prix': 1500,
            'periode': 'mois',
            'duree_jours': 30,
            'cours_limites': 0,  # illimité
            'quiz_limites': 0,  # illimité
            'examens_inclus': True,
            'certificats_inclus': True,
            'support_ia_prioritaire': True,
            'contenu_hors_ligne': True,
            'offre_semaine_gratuite': True,
            'pack_special': False,
        },
        # Packs spéciaux
        {
            'nom': 'Préparation BAC/BEPC',
            'type_pack': 'special',
            'description': 'Pack spécial pour la préparation aux examens nationaux',
            'prix': 4000,
            'periode': 'trimestre',
            'duree_jours': 90,
            'cours_limites': 0,
            'quiz_limites': 0,
            'examens_inclus': True,
            'certificats_inclus': True,
            'support_ia_prioritaire': True,
            'contenu_hors_ligne': True,
            'offre_semaine_gratuite': True,
            'pack_special': True,
            'reduction_pourcentage': 20,
            'conditions_speciales': 'Pack spécial pour les examens nationaux avec réduction de 20%',
        },
        {
            'nom': 'Pack Vacances',
            'type_pack': 'special',
            'description': 'Accès intensif pendant les vacances scolaires',
            'prix': 2000,
            'periode': 'mois',
            'duree_jours': 30,
            'cours_limites': 0,
            'quiz_limites': 0,
            'examens_inclus': True,
            'certificats_inclus': True,
            'support_ia_prioritaire': True,
            'contenu_hors_ligne': True,
            'offre_semaine_gratuite': False,
            'pack_special': True,
            'reduction_pourcentage': 15,
            'conditions_speciales': 'Pack spécial vacances avec réduction de 15%',
        },
        {
            'nom': 'Premium+ Annuel',
            'type_pack': 'premium',
            'description': 'Pack Premium annuel avec économies',
            'prix': 15000,
            'periode': 'annee',
            'duree_jours': 365,
            'cours_limites': 0,
            'quiz_limites': 0,
            'examens_inclus': True,
            'certificats_inclus': True,
            'support_ia_prioritaire': True,
            'contenu_hors_ligne': True,
            'offre_semaine_gratuite': True,
            'pack_special': True,
            'reduction_pourcentage': 25,
            'conditions_speciales': 'Pack annuel avec 2 mois gratuits (économie de 25%)',
        },
    ]
    
    for pack_data in packs:
        PackAbonnement.objects.get_or_create(
            nom=pack_data['nom'],
            defaults=pack_data
        )
    
    # Packs familiaux
    packs_familiaux = [
        {
            'nom': 'Pack Famille 2 enfants',
            'nombre_enfants': 2,
            'reduction_pourcentage': 20,
            'description': 'Pack familial pour 2 enfants avec réduction de 20%',
        },
        {
            'nom': 'Pack Famille 3+ enfants',
            'nombre_enfants': 3,
            'reduction_pourcentage': 30,
            'description': 'Pack familial pour 3 enfants ou plus avec réduction de 30%',
        },
    ]
    
    for pack_familial_data in packs_familiaux:
        PackFamilial.objects.get_or_create(
            nom=pack_familial_data['nom'],
            defaults=pack_familial_data
        )

def reverse_initial_packs(apps, schema_editor):
    PackAbonnement = apps.get_model('abonnements', 'PackAbonnement')
    PackFamilial = apps.get_model('abonnements', 'PackFamilial')
    
    # Supprimer les packs créés
    PackAbonnement.objects.filter(
        nom__in=['Gratuit', 'Standard', 'Premium', 'Préparation BAC/BEPC', 'Pack Vacances', 'Premium+ Annuel']
    ).delete()
    
    PackFamilial.objects.filter(
        nom__in=['Pack Famille 2 enfants', 'Pack Famille 3+ enfants']
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_packabonnement_packfamilial_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_packs, reverse_initial_packs),
    ]
