# Generated by Django 5.1.2 on 2025-09-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0003_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilisationAbonnement',
        ),
    ]
