# Generated by Django 5.1.2 on 2025-09-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0004_remove_utilisation_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='packfamilial',
            name='certificats_inclus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='conditions_speciales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='contenu_hors_ligne',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='cours_limites',
            field=models.IntegerField(default=0, help_text='0 = illimité'),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='duree_jours',
            field=models.IntegerField(default=30, help_text='Durée en jours'),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='examens_inclus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='offre_semaine_gratuite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='pack_familial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='periode',
            field=models.CharField(choices=[('semaine', 'Semaine'), ('mois', 'Mois'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('annee', 'Année')], default='mois', max_length=20),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='quiz_limites',
            field=models.IntegerField(default=0, help_text='0 = illimité'),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='support_ia_prioritaire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packfamilial',
            name='type_familial',
            field=models.CharField(choices=[('familial_2', 'Famille 2 enfants'), ('familial_3', 'Famille 3+ enfants'), ('familial_4', 'Famille 4+ enfants')], default='familial_2', max_length=20),
        ),
        migrations.AlterField(
            model_name='packfamilial',
            name='reduction_pourcentage',
            field=models.IntegerField(default=20, help_text='Réduction en pourcentage'),
        ),
    ]
