# Generated by Django 5.1.2 on 2025-09-01 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0005_packfamilial_certificats_inclus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusParrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_accumules', models.PositiveIntegerField(default=0, help_text='Nombre de semaines gratuites accumulées (max 7)')),
                ('bonus_utilises', models.PositiveIntegerField(default=0, help_text='Nombre de bonus déjà utilisés')),
                ('date_dernier_bonus', models.DateTimeField(auto_now=True, help_text='Date du dernier bonus reçu')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_parrainage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonus de parrainage',
                'verbose_name_plural': 'Bonus de parrainage',
            },
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_parrainage', models.CharField(help_text='Code de parrainage utilisé', max_length=20)),
                ('date_parrainage', models.DateTimeField(auto_now_add=True, help_text='Date de création du parrainage')),
                ('bonus_attribue', models.BooleanField(default=False, help_text='True si le bonus a été attribué au parrain')),
                ('date_bonus_attribue', models.DateTimeField(blank=True, help_text="Date d'attribution du bonus", null=True)),
                ('filleul', models.OneToOneField(help_text='Utilisateur parrainé', on_delete=django.db.models.deletion.CASCADE, related_name='parrain', to=settings.AUTH_USER_MODEL)),
                ('parrain', models.ForeignKey(help_text='Utilisateur qui parraine', on_delete=django.db.models.deletion.CASCADE, related_name='filleuls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
                'unique_together': {('parrain', 'filleul')},
            },
        ),
    ]
