# Generated by Django 5.1.2 on 2025-09-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0006_bonusparrainage_parrainage'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='source_parrainage',
            field=models.BooleanField(default=False, help_text="True si l'abonnement provient du système de parrainage"),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='date_filleul_bonus',
            field=models.DateTimeField(blank=True, help_text="Date d'attribution du bonus au filleul", null=True),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='filleul_bonus_attribue',
            field=models.BooleanField(default=False, help_text='True si le bonus a été attribué au filleul'),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='type_avantage_filleul',
            field=models.CharField(choices=[('semaine_gratuite', 'Semaine gratuite'), ('pack_bienvenue', 'Pack de bienvenue'), ('reduction_premiere', 'Réduction première commande')], default='semaine_gratuite', help_text="Type d'avantage offert au filleul", max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusparrainage',
            name='bonus_accumules',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de semaines gratuites accumulées'),
        ),
    ]
