# Generated by Django 5.1.2 on 2025-09-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0007_abonnement_source_parrainage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrainage',
            name='type_avantage_filleul',
        ),
        migrations.AlterField(
            model_name='parrainage',
            name='date_filleul_bonus',
            field=models.DateTimeField(blank=True, help_text="Date d'attribution de la semaine gratuite au filleul", null=True),
        ),
        migrations.AlterField(
            model_name='parrainage',
            name='filleul_bonus_attribue',
            field=models.BooleanField(default=False, help_text='True si la semaine gratuite a été attribuée au filleul'),
        ),
    ]
