# Generated by Django 5.1.2 on 2025-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0008_remove_parrainage_type_avantage_filleul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrainage',
            name='date_filleul_bonus',
            field=models.DateTimeField(blank=True, help_text="Date d'attribution du bonus au filleul", null=True),
        ),
        migrations.AlterField(
            model_name='parrainage',
            name='filleul_bonus_attribue',
            field=models.BooleanField(default=False, help_text='True si le bonus a été attribué au filleul'),
        ),
    ]
