# Generated by Django 5.1.2 on 2025-09-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0009_alter_parrainage_date_filleul_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='date_renouvellement',
            field=models.DateTimeField(blank=True, help_text='Date du dernier renouvellement', null=True),
        ),
        migrations.CreateModel(
            name='HistoriqueRenouvellement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_renouvellement', models.DateTimeField(auto_now_add=True, help_text='Date du renouvellement')),
                ('duree_ajoutee', models.PositiveIntegerField(help_text='Nombre de jours ajoutés')),
                ('montant_renouvellement', models.DecimalField(decimal_places=2, help_text='Montant du renouvellement', max_digits=10)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renouvellements', to='abonnements.abonnement')),
            ],
            options={
                'verbose_name': 'Historique de renouvellement',
                'verbose_name_plural': 'Historiques de renouvellements',
                'ordering': ['-date_renouvellement'],
            },
        ),
    ]
