# Generated by Django 5.1.2 on 2025-09-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0010_abonnement_date_renouvellement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cours_par_mois', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('max_quiz_par_mois', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('max_examens_par_mois', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('acces_cours_premium', models.BooleanField(default=False, help_text='Accès aux cours premium')),
                ('acces_ia_standard', models.BooleanField(default=False, help_text='Support IA standard')),
                ('acces_ia_prioritaire', models.BooleanField(default=False, help_text='Support IA prioritaire')),
                ('acces_certificats', models.BooleanField(default=False, help_text='Accès aux certificats')),
                ('acces_contenu_hors_ligne', models.BooleanField(default=False, help_text='Téléchargement de contenu')),
                ('acces_communautaire', models.BooleanField(default=False, help_text='Accès au forum communautaire')),
                ('support_prioritaire', models.BooleanField(default=False, help_text='Support prioritaire')),
                ('acces_prioritaire_nouveautes', models.BooleanField(default=False, help_text='Accès prioritaire aux nouveautés')),
                ('specialisation_examens', models.BooleanField(default=False, help_text='Spécialisé pour les examens')),
                ('contenu_examens_prioritaire', models.BooleanField(default=False, help_text='Contenu examens prioritaire')),
                ('nombre_enfants_max', models.PositiveIntegerField(default=0, help_text="Nombre maximum d'enfants")),
                ('profils_separes', models.BooleanField(default=False, help_text='Profils séparés pour chaque enfant')),
                ('suivi_familial', models.BooleanField(default=False, help_text='Suivi familial')),
                ('upgrade_reminder', models.BooleanField(default=False, help_text="Rappels d'upgrade")),
                ('teaser_content', models.BooleanField(default=False, help_text='Contenu teaser premium')),
                ('restriction_temps', models.BooleanField(default=False, help_text='Restriction temporelle')),
                ('restriction_contenu', models.BooleanField(default=False, help_text='Restriction de contenu')),
                ('restriction_examens', models.BooleanField(default=False, help_text="Restriction d'examens")),
                ('message_restriction', models.TextField(default='Vous avez atteint votre limite. Passez à un pack supérieur !', help_text='Message affiché quand les restrictions sont atteintes')),
                ('bonus_parrainage', models.BooleanField(default=False, help_text='Bonus pour parrainage')),
                ('bonus_inscription', models.BooleanField(default=False, help_text='Bonus pour inscription')),
                ('bonus_conversion_parrainage', models.BooleanField(default=False, help_text='Bonus de conversion parrainage')),
                ('bonus_conversion_standard', models.BooleanField(default=False, help_text='Bonus de conversion standard')),
                ('bonus_annuel', models.BooleanField(default=False, help_text='Bonus annuel')),
                ('acces_exclusif', models.BooleanField(default=False, help_text='Contenu exclusif')),
                ('source_parrainage', models.BooleanField(default=False, help_text='Source parrainage')),
                ('source_inscription', models.BooleanField(default=False, help_text='Source inscription')),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='abonnements.packabonnement')),
            ],
            options={
                'verbose_name': 'Permissions du pack',
                'verbose_name_plural': 'Permissions des packs',
            },
        ),
    ]
