# Generated by Django 5.1.2 on 2025-09-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0011_packpermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packabonnement',
            name='certificats_inclus',
        ),
        migrations.RemoveField(
            model_name='packabonnement',
            name='contenu_hors_ligne',
        ),
        migrations.RemoveField(
            model_name='packabonnement',
            name='cours_limites',
        ),
        migrations.RemoveField(
            model_name='packabonnement',
            name='examens_inclus',
        ),
        migrations.RemoveField(
            model_name='packabonnement',
            name='quiz_limites',
        ),
        migrations.RemoveField(
            model_name='packabonnement',
            name='support_ia_prioritaire',
        ),
        migrations.RemoveField(
            model_name='packfamilial',
            name='certificats_inclus',
        ),
        migrations.RemoveField(
            model_name='packfamilial',
            name='contenu_hors_ligne',
        ),
        migrations.RemoveField(
            model_name='packfamilial',
            name='cours_limites',
        ),
        migrations.RemoveField(
            model_name='packfamilial',
            name='examens_inclus',
        ),
        migrations.RemoveField(
            model_name='packfamilial',
            name='quiz_limites',
        ),
        migrations.RemoveField(
            model_name='packfamilial',
            name='support_ia_prioritaire',
        ),
    ]
