# Generated by Django 5.1.2 on 2025-09-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0012_remove_legacy_permission_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='packabonnement',
            name='code',
            field=models.CharField(blank=True, help_text='Code unique du pack (ex: pack-2, pack-3)', max_length=20, null=True, unique=True),
        ),
    ]
