# Generated by Django 5.1.2 on 2025-09-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0013_packabonnement_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packabonnement',
            name='code',
        ),
    ]
