# Generated by Django 5.1.2 on 2025-09-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0014_remove_packabonnement_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementwave',
            name='pack_id',
            field=models.IntegerField(blank=True, help_text='ID du pack à créer après paiement', null=True),
        ),
        migrations.AddField(
            model_name='paiementwave',
            name='renouvellement_auto',
            field=models.BooleanField(default=False, help_text='Renouvellement automatique'),
        ),
        migrations.AddField(
            model_name='paiementwave',
            name='utilisateur_id',
            field=models.IntegerField(blank=True, help_text="ID de l'utilisateur", null=True),
        ),
        migrations.AlterField(
            model_name='paiementwave',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonnements.abonnement'),
        ),
    ]
