# Generated by Django 5.1.2 on 2025-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0015_paiementwave_pack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementwave',
            name='parent_id',
            field=models.IntegerField(blank=True, help_text='ID du parent qui effectue le paiement (pour les abonnements enfants)', null=True),
        ),
    ]
