# Generated by Django
from django.db import migrations

def ajouter_prix_packs_familiaux(apps, schema_editor):
    PackFamilial = apps.get_model('abonnements', 'PackFamilial')
    
    # Définir les prix des packs familiaux
    packs_familiaux_data = [
        {
            'nom': 'Pack Famille 2 enfants',
            'prix': 2500,
            'nombre_enfants': 2,
            'reduction_pourcentage': 20,
            'description': 'Pack familial pour 2 enfants avec réduction de 20%',
        },
        {
            'nom': 'Pack Famille 3 enfants',
            'prix': 4000,
            'nombre_enfants': 3,
            'reduction_pourcentage': 25,
            'description': 'Pack familial pour 3 enfants avec réduction de 25%',
        },
        {
            'nom': 'Pack Famille 4 enfants',
            'prix': 5000,
            'nombre_enfants': 4,
            'reduction_pourcentage': 30,
            'description': 'Pack familial pour 4 enfants avec réduction de 30%',
        },
    ]
    
    for pack_data in packs_familiaux_data:
        pack, created = PackFamilial.objects.get_or_create(
            nom=pack_data['nom'],
            defaults=pack_data
        )
        if not created:
            # Mettre à jour le prix si le pack existe déjà
            pack.prix = pack_data['prix']
            pack.nombre_enfants = pack_data['nombre_enfants']
            pack.reduction_pourcentage = pack_data['reduction_pourcentage']
            pack.description = pack_data['description']
            pack.save()

def reverse_ajouter_prix_packs_familiaux(apps, schema_editor):
    # Ne rien faire en cas de rollback
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0016_paiementwave_parent_id'),
    ]

    operations = [
        migrations.RunPython(ajouter_prix_packs_familiaux, reverse_ajouter_prix_packs_familiaux),
    ]
