# Generated by Django 5.1.2 on 2025-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0017_ajouter_prix_packs_familiaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packabonnement',
            name='type_pack',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('premium', 'Premium'), ('special', 'Pack Spécial'), ('famille', 'Pack Familial')], max_length=20),
        ),
    ]
