# Generated by Django 5.1.2 on 2025-08-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ordre', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Niveau scolaire',
                'verbose_name_plural': 'Niveaux scolaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icone', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=7)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.niveauscolaire')),
            ],
            options={
                'ordering': ['niveau__ordre', 'ordre'],
                'unique_together': {('nom', 'niveau')},
            },
        ),
    ]
