# Generated by Django 5.1.2 on 2025-08-10 23:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.BooleanField(default=False)),
                ('temps_lecture', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Progression contenu',
                'verbose_name_plural': 'Progressions contenus',
            },
        ),
        migrations.CreateModel(
            name='ProgressionChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('maitrise', 'Maîtrisé')], default='non_commence', max_length=20)),
                ('pourcentage_completion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temps_etudie', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.chapitre')),
            ],
            options={
                'verbose_name': 'Progression chapitre',
                'verbose_name_plural': 'Progressions chapitres',
            },
        ),
    ]
