# Generated by Django 5.1.2 on 2026-01-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
        ('cours', '0001_initial'),
        ('progression', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionchapitre',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressioncontenu',
            name='contenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.contenuchapitre'),
        ),
        migrations.AddField(
            model_name='progressioncontenu',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressionmatiere',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressionmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='progressionchapitre',
            unique_together={('etudiant', 'chapitre')},
        ),
        migrations.AlterUniqueTogether(
            name='progressioncontenu',
            unique_together={('etudiant', 'contenu')},
        ),
        migrations.AlterUniqueTogether(
            name='progressionmatiere',
            unique_together={('etudiant', 'matiere')},
        ),
    ]
