# Generated by Django 5.1.2 on 2025-08-15 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0002_initial_data'),
        ('progression', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('maitrise', 'Maîtrisé')], default='non_commence', max_length=20)),
                ('pourcentage_completion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temps_etudie_total', models.PositiveIntegerField(default=0, help_text='Temps total en secondes pour tous les chapitres de cette matière')),
                ('nombre_chapitres_termines', models.PositiveIntegerField(default=0)),
                ('nombre_chapitres_total', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.matiere')),
            ],
            options={
                'verbose_name': 'Progression matière',
                'verbose_name_plural': 'Progressions matières',
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
    ]
