# Generated by Django 5.1.2 on 2026-01-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('duree_estimee', models.PositiveIntegerField()),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='academic_structure.matiere')),
                ('prerequis', models.ManyToManyField(blank=True, to='cours.chapitre')),
            ],
            options={
                'ordering': ['matiere', 'numero'],
                'unique_together': {('matiere', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ContenuChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='cours/pdf/')),
                ('url_video', models.URLField(blank=True)),
                ('contenu_html', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='cours.chapitre')),
            ],
            options={
                'ordering': ['chapitre', 'ordre'],
                'unique_together': {('chapitre', 'ordre')},
            },
        ),
    ]
