# Generated by Django 5.1.2 on 2025-08-15 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='type_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='examens.typeexamen'),
        ),
    ]
