# Generated by Django 5.1.2 on 2026-01-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('condition_type', models.CharField(choices=[('chapitres_termines', 'Chapitres terminés'), ('quiz_parfait', 'Quiz parfait'), ('quiz_reussis', 'Quiz réussis'), ('temps_etude', "Temps d'étude"), ('progression_matiere', 'Progression matière'), ('matiere_complete', 'Matière complète'), ('matieres_terminees', 'Matières terminées'), ('programme_complet', 'Programme complet'), ('premier_chapitre', 'Premier chapitre')], max_length=30)),
                ('condition_valeur', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=10)),
                ('icone', models.CharField(default='fa-trophy', help_text='Icône FontAwesome (ex: fa-star)', max_length=50)),
                ('couleur', models.CharField(default='warning', help_text='Couleur Bootstrap (primary, success, warning, etc.)', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='gamification.badge')),
            ],
            options={
                'verbose_name': 'Badge étudiant',
                'verbose_name_plural': 'Badges étudiants',
            },
        ),
    ]
