# Generated by Django 5.1.2 on 2025-08-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('condition_type', models.CharField(choices=[('chapitres_termines', 'Chapitres terminés'), ('quiz_parfait', 'Quiz parfait'), ('temps_etude', "Temps d'étude"), ('progression_matiere', 'Progression matière')], max_length=30)),
                ('condition_valeur', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
            ],
            options={
                'verbose_name': 'Badge étudiant',
                'verbose_name_plural': 'Badges étudiants',
            },
        ),
    ]
