# Generated by Django 5.1.2 on 2025-08-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='couleur',
            field=models.CharField(default='warning', help_text='Couleur Bootstrap (primary, success, warning, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='icone',
            field=models.CharField(default='fa-trophy', help_text='Icône FontAwesome (ex: fa-star)', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('chapitres_termines', 'Chapitres terminés'), ('quiz_parfait', 'Quiz parfait'), ('quiz_reussis', 'Quiz réussis'), ('temps_etude', "Temps d'étude"), ('progression_matiere', 'Progression matière'), ('matiere_complete', 'Matière complète'), ('matieres_terminees', 'Matières terminées'), ('programme_complet', 'Programme complet'), ('premier_chapitre', 'Premier chapitre')], max_length=30),
        ),
    ]
