# Generated by Django 5.1.2 on 2025-08-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_add_badge_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeetudiant',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='gamification.badge'),
        ),
    ]
